### ISSUE TITLE
Unable to get mobile responsiveness working

### ISSUE THREAD

**Issue by cmvanb** [beercss/beercss#102]
Hello,

I am building a web app with BeerCSS. I love how easy it is to get off the ground quickly! It looks great on desktop, but unfortunately does not seem to be responsively scaled on mobile. I am using `firefox`, but I also see the same issue in `chromium` browsers.

App: https://codemu.ch/cookbook
Source Code: https://github.com/cmvanb/cookbook
Base HTML template: https://github.com/cmvanb/cookbook/blob/master/cookbook/templates/base.html
Custom CSS: https://github.com/cmvanb/cookbook/blob/master/cookbook/static/main.css

When I inspect the HTML/CSS I don't see any major differences in structure. I must be missing something to enable mobile responsiveness, any idea what I'm doing wrong?

Here is a visual comparison:

App             |  BeerCSS
:-------------------------:|:-------------------------:
![cookbook](https://user-images.githubusercontent.com/3225873/204820948-52943cb1-297f-43fd-9fab-e41879e406b7.jpg)  |  ![beercss](https://user-images.githubusercontent.com/3225873/204820967-83554b0c-de75-4e3a-8b46-30ae67fc9032.jpg)

best regards,
Casper

**Comment by AlTrAugsburg** [comment]
Hi @cmvanb,

it seems like you forgotten to set the viewport on the website. Just add this line to your \<head\> and it should work:

```
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
```

Without that, beercss and many other CSS-Frameworks won't work, because without viewport, the browser doesn't know what width/height to calculate with. More information here: https://developer.mozilla.org/en-US/docs/Web/CSS/Viewport_concepts

Also I would recommend always to start with the template in the README, than you should be on the safe side: https://github.com/beercss/beercss#html

**Comment by cmvanb** [comment]
That works perfectly. Thank you for your quick and informative response!
