### ISSUE TITLE
Use SVGs instead of Material Symbols

### ISSUE THREAD

**Issue by coffeeandwork** [beercss/beercss#126]
Following the discussion here: https://github.com/beercss/beercss/issues/86#issuecomment-1336219024, I am creating this issue to confirm with @leonardorafael, @laurentpayot (who provided feedback on #86 regarding SVG usage), and anyone else, that this idea is acceptable to this project, before I put in time to create PR(s).

**Comment by laurentpayot** [comment]
I’m 100% for the use of SVG icons instead of a font, as long as we find a way to add our own icons if needed (for instance by using a [custom data attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) instead of a fixed set of icon CSS classes).
I’m using [Material Icons](https://github.com/Templarian/MaterialDesign-SVG) because official Material Design icon sets like Material Symbols are far too limited, thus the need of a customizable system to use Material Icons SVGs as icons. Or simply switching to Material Icons to directly use their _huge_ set of SVG icons.

But only @leonardorafael will decide :wink:

**Comment by leonardorafael** [comment]
Seems ok to me, how do you use svg aproach in beercss @laurentpayot ? Can you show some examples?

**Comment by laurentpayot** [comment]
@leonardorafael I tried a couple of things at https://codepen.io/laurentpayot/pen/yLxVPYB My approach was to allow any icons via their URL.


- The simplest integration would be to put the SVG `img` inside the `i` tag. The resulting icon is a bit bigger than the current Beercss icon so I guess some CSS rules have to be added for `i > img`:
```html
<i class="extra">
  <img src="https://cdn.jsdelivr.net/npm/@mdi/svg@7.1.96/svg/account-circle-outline.svg"></img>
</i>
```

- It is possible to use a custom element for this to have a shorter syntax. On the codepen example the MDI CDN is hard-coded but it should be possible to allow self-hosted MDI SVG icons.
```html
<icon-svg name="account-circle-outline" size="extra"></icon-svg>
```

- I thought it would be easy to set the icon content from a custom data attribute with the[`attr()`](https://developer.mozilla.org/en-US/docs/Web/CSS/attr) CSS function but unfortunately it is [not yet implemented  in any browser](https://caniuse.com/css3-attr) :man_facepalming:

I don’t know what @coffeeandwork has in mind. Is it to put the SVG content of a finite set of icons into the Beercss?

**Comment by leonardorafael** [comment]
Done in https://github.com/beercss/beercss/releases/tag/v3.1.0

**Comment by laurentpayot** [comment]
Thank you so much for all this amazing work @leonardorafael! This new realease is awesome. Cheers! :beers:
