### ISSUE TITLE
Cross framwork components

### ISSUE THREAD

**Issue by janat08** [beercss/beercss#130]
There is some package developed by qwik or unjs people that tries to make components cross framework, and some other package with a website for it. I'm interested in svelte implementation.

**Comment by leonardorafael** [comment]
Hi,

I think the standard HTML and CSS are ready to use in any JS framework. Am I wrong? I can't see any reason to convert a `<button>`, `<article>`, `<nav>` or any other element of Beer CSS into component. The elements are very simple by default and you can do the job with just HTML. Except if they need some extra logic rather than default `active` trigger.

Maybe the `field` elements can be components. But this is a particular use case of your project, that depends to add masks, validations, to render an auto-complete, to render a custom datepicker etc... Vue, Svelte, React and others can handle this easily. I recommend to translate into component in this cases, but just for your project, for now. We need to mature this idea.

**Comment by janat08** [comment]
The library has been converted to vue. I meant mitosis js.

**Comment by KicKerBNU** [comment]
@janat08 Thanks for your contribution.

![image](https://github.com/beercss/beercss/assets/43939417/d5e19844-6fc1-456d-b80d-5e29b5833dce)

**Comment by janat08** [comment]
Well, but then qwik and svelte beat out vue by quiet a bit, and there're surely complications when doing SSR with qwik but vue components.
