### ISSUE TITLE
Close menu dropdown when clicking it again

### ISSUE THREAD

**Issue by crypnull** [beercss/beercss#155]
I'm not sure if it's intended, but the menu example on the BeerCSS website does not close when clicking the button again when it's open.

**Comment by leonardorafael** [comment]
The default behavior is show the menu when is focused on parent element. But, you can add `<menu>` outside of element and trigger it manually too.

https://github.com/beercss/beercss/blob/main/docs/MENU.md

**Comment by cryptanym** [comment]
Clicking on a button that has data-ui="#menu" or onclick="ui('#menu');" when it is already open does not close it, unless you click off or on another button, it should toggle to closed when you run ui('#menu'); and it's already open, it looks like it tries to open the same button twice because it removes and readds the active class very quickly.

**Comment by leonardorafael** [comment]
Fixed in v3.2.5
