### ISSUE TITLE
Masonry Grid

### ISSUE THREAD

**Issue by crypnull** [beercss/beercss#184]
A masonry grid system would be very useful, especially for articles and media galleries, both horizontal and vertical, but mainly horizontal is what I need.

Here is an implantation in another CSS framework I like a lot.
https://getuikit.com/assets/uikit/tests/grid-masonry.html

**Comment by KicKerBNU** [comment]
Looks like grid masonry is not cross-browser supported yet
https://caniuse.com/?search=masonry
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Masonry_Layout

**Comment by leonardorafael** [comment]
We can simulate a masonry with `column-count` https://codepen.io/leo-bnu/pen/YzRYwBm

But the order of things is not in "Z pattern". And this is not responsive, needs to add some media queries to change the collumn count according to user screen.

**Comment by acroyear** [comment]
It appears as though Material Design doesn't mention masonry directly (it is shown in the Cards guidance section) since it is in the web standards (just not implemented anywhere). So as such, if beercss's primary goal is implementing material, then it would imply that one should get masonry specific from another as that's not a specific design pattern for Material.

**Comment by leonardorafael** [comment]
Closed, because this is inside another issue.
