### ISSUE TITLE
Number input 

### ISSUE THREAD

**Issue by InsightfulFuture** [beercss/beercss#185]
https://github.com/beercss/beercss/assets/109481728/daa48885-7a34-4348-ad93-3f96c4872a16

I don't think it is intentional, but when you type a number and then e and blur, the input is cleared. Possibly just prevent the user from typing e in the first place?

Example solution:
```
const onKeyDown=(e) => (e.keyCode === 69 
    // Checking for + or -
    || e.keyCode === 189 ||
    e.keyCode === 187 &&
    e.preventDefault();
```

**Comment by leonardorafael** [comment]
Hi @InsightfulFuture , It's intentional. We need to clear invalid values from input number to label up. The default behavior of browsers are very confusing with input numbers. Firefox clear invalid values after sometime. Chrome not clear it (and you can't access that invalid value with js or css).

Try input invalid values here and see what the browser does, https://codepen.io/leo-bnu/pen/KKGrXxv to better, understand this scenario.
