### ISSUE TITLE
classless version

### ISSUE THREAD

**Issue by janat08** [beercss/beercss#222]
There're classless css frameworks that apply styles to html tags. The appeal of those is that transitioning to something like this takes no effort.

**Comment by leonardorafael** [comment]
Hi @janat08 ,

I agree with you.
We are trying to do that.
We already use html tags like `<dialog>`, `<article>`, `<button>`, `<menu>`, `<nav>`, `<main>`, `<header>`, `<footer>`, without any extra class to work as default.
We can't go to fully classless because the variants of Material Design 3.
And styling with attribute `data-*` is a bit ugly for me.
