### ISSUE TITLE
Incompatibility with other libraries

### ISSUE THREAD

**Issue by WilliamSoler** [beercss/beercss#290]
I am currently using BeerCSS in one project but I came across an issue when I wanted to use another library for rendering maps.

The labels when hovering over the maps were not showing. I end up tracking the issue to the BeerCSS CSS file. Specifically in the following block:

```
* {
  -webkit-tap-highlight-color: transparent;
  position: relative;
  vertical-align: middle;
  color: inherit;
  margin: 0;
  padding: 0;
  border-radius: inherit;
  box-sizing: border-box;
}
```

on [code](https://github.com/beercss/beercss/blob/15104221584466af436a09a817be80865e1d444c/src/cdn/helpers/reset.css#L1 )

Is there any other option than to apply this styling to all elements? This makes it difficult to work with BeerCSS and other libraries because it causes incompatibilities that are difficult to override especially if the HTML is created dynamically with JS

What workaround would be the best to enable this styling for BeerCSS-styled HTML elements?

**Comment by leonardorafael** [comment]
Hi @WilliamSoler,

The project of Beer CSS doesn't delivery any guarantee that using another UI lib will work, because it styles directly HTML semantic tags. I would to suggest to use the map on different context like `iframe` or try to style as `all: revert`:

```html
<iframe src="/map"></iframe>
```

```html
<div style="all: revert">
  <div id="map"></div>
</div>
```

Using `all: revert` will revert to default styles from browser. In theory, all child element must work as expected. Maybe we can create a helper called "revert" or "revert-all" to do that.

**Comment by dabreegster** [comment]
Almost didn't spot that there's now a [scoped version](https://github.com/beercss/beercss?tab=readme-ov-file#scoped-version) that solves this problem, so just noting it for future reference. Thanks for getting that to work!
