### ISSUE TITLE
eiquetas h responsives

### ISSUE THREAD

**Issue by ximosa** [beercss/beercss#314]
Solo por contribuir seria interesante poner en este css las etiquetas h responsives.
Por ejemplo
@media (max-width: 768px) {
  h1 { font-size: 1.8em; }
  h2 { font-size: 1.6em; }
  h3 { font-size: 1.4em; }
  h4 { font-size: 1.2em; }
  h5 { font-size: 1em; }
}
Saludos

**Comment by luminarious** [comment]
Material Design docs basically say that Display styles should only be used for h1 or hero section texts and h2, h3, h4 should be using headline styles.

Responsive typography is even more confusing, because Material Design itself does not use it at all (default styles are meant for mobile). Larger screens use different layouts, but text sizes are meant to stay same. Android TV uses CSS scaling so that the screen is 960×540 even on a 4k screen and everything scales uniformly.

That said, I did find an older image with an example of how the font sizes could be adjusted on the type scale: https://www.figma.com/design/w4Ro1cBkcyfBPQUDTwqZnc/T%C3%BCpograafia?node-id=636-2&t=i5kRIcMxQ3DpBSlw-1
