### ISSUE TITLE
What are the width class available and why using sibling selector for article?

### ISSUE THREAD

**Issue by UdayKiranPadhy** [beercss/beercss#325]
Hi team , thank you for the awosome project .
I have 2 questions :- 

1. Are there any width class available ?
I would like to have container of constant width ( want to have some constant variable value for with like --small-width in library). 
I have tried "small" , "medium", "large" classes but those class only work on increasing the height of the container.
Can we have similar classes for width ?

2. Do we have any good reason why are having direct sibling selector css rules ? 
<img width="1728" alt="Screenshot 2024-06-29 at 9 04 15 PM" src="https://github.com/beercss/beercss/assets/58071209/f4bd5324-b84a-4665-a9ab-29805b3a1b0d">

As you can see there is some disturbance because of beer css siblings selector if i use consecutive <article> tag . It took me 30mins to figure out what is the issue behind it. Since i am applying same classes to previous element why are the next elements having such disturbance. 

I think if it is working as expected it shall be documented or atleast showed some example for this use case.

**Comment by leonardorafael** [comment]
Hi @UdayKiranPadhy , you can use the `no-margin` helper in your case. But there are others helpers here https://github.com/beercss/beercss/blob/main/docs/HELPERS.md#margins

And you can combine the margin helpers like:

`no-margin top-margin` > no margin on top
`large-margin top-margin left-margin` > large margin on top and left
`small-margin vertical-margin` > small margin on top and bottom

By default the project add a margin when repeat the tags:

`* + article`, `* + nav`, etc...

**Comment by UdayKiranPadhy** [comment]
Ok @leonardorafael  so thats an expected behaviour , Got it. Can i please know the reason behind that css ? How does it actually helps, in what use case it could be useful , just asking from educational point of view .

Also do we have width specify classes ?

**Comment by leonardorafael** [comment]
Sure, I can explain @UdayKiranPadhy .

I think we already have a helper like your `planner`. You can use the `row` element (as line container) and `grid` element (as grid system container).

The ´row` element was created to render lines (rows):

```html
<div class="row">
  <article class="max">...</article>
  <article class="max">...</article>
</div>
```

Why we created the `max` helper here? Because it will fit all row with the element.

Why `max` is not the default behavior? Because on a `row` is more common to use clickable/text elements like:

```html
<div class="row">
  <button>...</button>
  <i>...</i>
  <a></a>
  <h6 class="max">...</h6>
</div>
```

Why we decided to use a top margin when use `* + article`, `* + nav` or `* + *`? Because this is the almost used behavior, looh the code below:

```html
<article></article>
<article></article>
<nav></nav>
```

We expect that this render a article below article and a nav (and this needs space). This is our explanation about it.

But you can stil use your planner if you add the rule:

```css
.planner > * {
  margin-block: 0;
}

**Comment by leonardorafael** [comment]
Oh I forgot to answer about `width` helpers, https://github.com/beercss/beercss/blob/main/docs/HELPERS.md#sizes

We have this `auto-width`, `small-width`, `medium-width`, `large-width`

**Comment by UdayKiranPadhy** [comment]
Thanks @leonardorafael  for your time explaining things so clearly .
