### ISSUE TITLE
Kudos! Que Legal! Question BeerCSS + React examples?

### ISSUE THREAD

**Issue by cameronelliott** [beercss/beercss#35]
Hi you guys, I recently found BeerCSS, as I am trying to choose a CSS framework for a project.

I think BeerCSS is really great! 
I am super impressed with how minimalistic the HTML is also!

My question is:
Are there any examples of BeerCSS with React?
I am a newer front-end developer, so while I think I can figure it out, I just
want to ask if there is something on the web I could not find.

Thanks for any help or pointers.

Cameron / Seattle
PS, I told my friend in Riberao Preto/SP, how impressed I was of the work of two designers in Blumenau/SC.
So cool you guys!

**Comment by leonardorafael** [comment]
Hey @cameronelliott thanks!

Beercss is focused in the html/css. You can use it in any js framework. To use with React, you need to install/import beercss into your project, see more here https://github.com/beercss/beercss#getting-started

**Comment by myrp-everton** [comment]
Hello @cameronelliott 

With Vue JS and Vue CLI we can just import it at main.js, after installing it with `npm i beercss`
![image](https://user-images.githubusercontent.com/58529622/152637209-59cad6db-8b81-4a55-92fd-5ae2b60240cc.png)

If you find any problem using it with React you can always open an issue here.

Thanks

**Comment by denno020** [comment]
Hey @cameronelliott, I just wanted to add my two-cents here. I'm using BeerCSS in a React app, and it really was as easy as adding

```
import 'beercss';
```

to the `main.js` file. This is the file that contains `ReactDOM.render....`.

I haven't imported the JS, so there are some instances where we have to reverse engineer the JS required in order to get elements to work, the perfect examples being the dropdown and modal elements. It isn't obvious in the documentation, at least not to me, what exactly needs to change in order for the modal/dropdown to work, but some quick dev tools snooping and toggling the dropdown/modal shows that all we need to do is add a `active` class name to our dropdown/modal when we want it to be visible. There are likely to be more instances where we have to reverse engineer, but I'm only early on in my Beer journey, so I haven't yet come across anymore.

I've moved to Beer after starting my project with another Material Design library, and I have to say, it's a breath of fresh air that we don't have to add a tonne of class names to style a button!

**Comment by cameronelliott** [comment]
I think that's plenty of ways to make this happen, thanks!
