### ISSUE TITLE
Can't align al top right

### ISSUE THREAD

**Issue by bubnenkoff** [beercss/beercss#39]
Hello! I would like to do this:
![изображение](https://user-images.githubusercontent.com/6514326/153167391-87c40677-240e-4f0b-b43d-718edbe91228.png)

But it's not working....

https://codepen.io/bubnenkoff/pen/jOaBZgO

**Comment by leonardorafael** [comment]
Hi @bubnenkoff 

Some points in your code:

- add `top-align` helper to `<article>` (because is the parent)
- add `no-margin` helper to `<ul>` (because `<ul>` has margins added by browser)
- we will improve the docs of beercss soon, but we don't want another bored docs like others frameworks
- now try the code  👇



```
<article class="white top-align">
  <button class="small border">AAA</button>
  <button class="small border">BBB</button>
  <div style="column-count: 4;">
    <ul class="no-margin">
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
    </ul>
  </div>
</article>
```

**Comment by bubnenkoff** [comment]
Bit thanks!
