### ISSUE TITLE
Question: How to init the javascript?

### ISSUE THREAD

**Issue by rejas** [beercss/beercss#43]
Hi, thanks for the library, but I am a little lost right now. 

I want to add it to my svelte app and adding it via "npm install" and "import beercss" works insofar as the css is applied.

But the tabs for example dont work. How to switch the dark/light theme also eludes me. 

In the tab codepen (https://codepen.io/kickerbnu/pen/bGBYMZR) I saw a call to ui(). Is that necessary to do so that the javascript is triggered?

Thanks in advance for any help.

**Comment by leonardorafael** [comment]
Hi @rejas 🖖

There are 3 ways to trigger elements. But we recommend the autoinit option because It's more easy. After render the html on Svelte (usually in onMount), you can call `ui()` or `window.ui()`.

```
// html
<div class="tabs">
  <a class="active" data-ui="#tab1">Tab 1</a>
  <a data-ui="#tab2">Tab 2</a>
  <a data-ui="#tab3">Tab 3</a>
</div>
<div id="tab1" class="page padding active">
  <h5>Tab 1</h5>
</div>
<div id="tab2" class="page padding">
  <h5>Tab 2</h5>
</div>
<div id="tab3" class="page padding">
  <h5>Tab 3</h5>
</div>

// js
onMount(() => {
  ui();
});
```

I do not test the code above, this works for you @rejas ?
We will improve the docs soon.

**Comment by leonardorafael** [comment]
Oh, I forgot. To change the default theme to dark add `is-dark` class to `body` element. To back to light just remove it.

**Comment by m4heshd** [comment]
@leonardorafael, Thank you for the amazing library.

Unfortutely it doesn't work for me on Vue's `mounted` LH. Had to run it when the `readyState` was "complete".

```js
document.onreadystatechange = () => {
  if (document.readyState === "complete") {
    window.ui();
  }
};
```

**Comment by leonardorafael** [comment]
Hey @m4heshd 

Yes If you want to use autoinit option you only need to call `ui()` after render the html. Another option is add/remove "active" class to elements by your own.

Cheers 🍺

**Comment by rejas** [comment]
> I do not test the code above, this works for you @rejas ?

Yes, it did. Thanks a lot! Cant wait for the doc improvements ;-)

**Comment by m4heshd** [comment]
> If you want to use autoinit option you only need to call `ui()` after render the html

Sadly this doesn't work on nodes that are dynamically loaded. Like router views. As it should since there can't be preset event handles on those children AFAIK. But I can totally live with running it on all dynamic components separately. Perfectly fine. 😊 

Is there a possibility of using event delegation? I think that would solve this edge case related to dynamic elements. But that feels like a big refactor. _(Even though I'm suggesting this, haven't had the time to look through `Beercss` source)_

**Comment by myrp-leonardo** [comment]
Hello @m4heshd ,

I think we do not need to call `ui()` every time in every component. Only if we have a `data-ui` attribute in our html output. In Vue, we usually call `ui()` on `mounted()` and on `Vue.nextTick` (after a state update , you can call `Vue.nextTick` and this will be executed after apply the updates on html). I do not know Svelte and your lifecycles, but I think they are the same way.

It's easy to use. And It has less calls to `ui()` that you think.

Good luck with your beer journey 🍺

**Comment by m4heshd** [comment]
Hi @myrp-leonardo,

> I think we do not need to call `ui()` every time in every component.

We need to if the component is dynamically mounted and contains elements that need JS intervention for Beer functionality.

> we usually call `ui()` on `mounted()` and on `Vue.nextTick`

I already use `nextTick()` but only if it triggers a re-render. If not it's quite unnecessary since it would be adding a lot more work on the page, possibly wasting a ton of resources.

> Good luck with your beer journey 🍺

Thank you and good luck to you as well. 😊
