### ISSUE TITLE
Input value clash with Label on init

### ISSUE THREAD

**Issue by dutscher** [beercss/beercss#45]
hi there,
thanks for your hard work to get some beer in the game :D
i found this on init, an input with filled value:
![image](https://user-images.githubusercontent.com/14682/155814723-af7f6505-d4ec-4b5f-96e7-c8377ff44eec.png)

And this if a label has whitespace:
![image](https://user-images.githubusercontent.com/14682/155814887-3d89251b-216d-417c-8511-34294dc8ce8f.png)

cheers

**Comment by leonardorafael** [comment]
Hum, I will investigate it. Do you call `ui()` after html output?

All best!

**Comment by leonardorafael** [comment]
Hi @dutscher ,

I'm trying to investigate this behavior with Svelte here https://codesandbox.io/s/label-up-svelte-beercss-lmfmi4

Any change on `label` (and this includes a re-render like `if`) you need to call `ui()` after `tick()`. This occurs because beercss needs to update the `clip-path` property based on text size of the `label` . This behavior applies to `field` element  with `border` helper only.

Hope this helps, you!

**Comment by leonardorafael** [comment]
I will close this issue, ok? Anyway I fixed a label ratio issue here too https://github.com/beercss/beercss/releases/tag/v2.0.16.

And feel free to reopen this issue at anytime.
