### ISSUE TITLE
Introduce tiny chips and buttons

### ISSUE THREAD

**Issue by saloniamatteo** [beercss/beercss#55]
Hello everyone and BeerCSS devs,
I like this CSS framework! It's really useful, modern-looking, and simple 😄 

Can you guys add the `tiny` class to both chips and buttons? So it would look something like the picture below (I'm talking about the text that says "Gentoo Linux")
![label](https://user-images.githubusercontent.com/28765699/162579353-dae9092d-1a02-4066-bcd2-49d99cb471c4.png)

This could be especially useful to create label-looking elements. When writing paragraphs and we need to add labels, I feel chips and buttons, even with the `small` class, are just too big and mess up the text top & bottom alignment.

Thanks in advance!
Matteo

**Comment by leonardorafael** [comment]
Hey @saloniamatteo 

We are studying your case. I think this can be used for you https://codepen.io/leo-bnu/pen/LYeJQOL. But it will have one side effect. This side effect is not too bad for me, because forces user to use the right element (`<nav>` instead `<p>`).

### Pros:
1) can configure line spacing
2) all buttons and chips are auto sized

### Cons:
1) has one side effect (for people who use `<p>` instead `<nav>` for navigation)

### Can we to proceed with this? 

We need some feedback here @laurentpayot @KicKerBNU @saloniamatteo @denno020 @myrp-leonardo . Please, react this comment with 👍 or 👎**

**Comment by saloniamatteo** [comment]
@leonardorafael I like your implementation! However, I noticed chips get placed slightly lower than the normal text, at least on mobile. (FF 98.2.0)

Also, I didn't understand the last bit, "has one side effect (for people who use `<p>` instead of `<nav>` for navigation)", what seems to be the issue?

Other than that, I think this looks pretty good.

**Comment by leonardorafael** [comment]
@saloniamatteo can you access again? I add the side effect https://codepen.io/leo-bnu/pen/LYeJQOL

**Comment by saloniamatteo** [comment]
@leonardorafael Oh yes, I see it;
In the following snippet of code

```css
p > button,
p > .button,
p > .chip,
p > .circle,
p > .square,
p > .diamond {
  position: relative;
  padding: 0;
  margin: 0;
[...]
```

if you remove the initial `p > button` and scroll down to "side effects", you can see the buttons get bigger, as if they were "fixed" (granted, they still need left & right inner padding to make them look like the buttons below `nav > button`)

A possible fix would be to implement this only with the class `.tiny`, just like in the other examples (e.g. `<p class="button tiny...`, and `<p class="chip tiny...`, both to get even smaller chips and buttons. This same style could also be applied to the class `.label` and the tag `<label>`. What do you think?

**Comment by myrp-leonardo** [comment]
I think we will go in `tiny` way and add  `space` helpers to `<p>` element too. In this way we do not have side effects and the implementation will have the haf size of another. See it again here https://codepen.io/leo-bnu/pen/LYeJQOL

Thanks @saloniamatteo

**Comment by leonardorafael** [comment]
I think we will go in tiny way and add space helpers to <p> element too. In this way we do not have side effects and the implementation will have the haf size of another. See it again here https://codepen.io/leo-bnu/pen/LYeJQOL

Thanks @saloniamatteo

**Comment by saloniamatteo** [comment]
@leonardorafael I'm glad I was able to help -- I was seeing your live edits while I was studying the code and saw the side effects disappear, now they work as they should 😊

**Comment by laurentpayot** [comment]
@leonardorafael  I wish every request could be fulfilled but I had to downvote this one for the following reasons:

1. It is nowhere in the Material Design specs. They are even [against too many buttons/chips on a screen](https://m3.material.io/components/buttons/guidelines#:~:text=Too%20many%20buttons%20on%20a%20screen%20disrupts%20the%20visual%20hierarchy.).
2. Normal links are supposed to be used for this (["buttons do things, links go places"](https://css-tricks.com/building-good-download-button/#aa-buttons-do-things-links-go-places)), so this is not a common nor best practice.
3. If added this would make the bundle bigger.
4. If people really want this feature they can simply add the codepen CSS discussed above.

So as @saloniamatteo’s particular issue can be fixed simply by adding the codepen CSS to his styles, why should we add a non-Material feature to everyone’s bundle?

**Comment by saloniamatteo** [comment]
@laurentpayot,

1. The Material Design _guidelines_ say not to clutter the **UI** with too many buttons, nothing against button styles provided by the CSS. Since we're not adding a button style, but rather providing a smaller version, I don't see a problem.

2. What's wrong with that? If you see the initial image, you can see a label, that is actually a link, used to navigate, of course. In order to achieve that, with this fix I could write the following: `<a class="button tiny indigo white-text" href=...` and it would work as intended, without any issues.

3. It wouldn't be noticeable, at all. Considering you provide minified versions of the CSS, the "impact" would be minimal, close to 0.

4. I don't think people that actually want to be productive will:
4.1. Import BeerCSS
4.2. Since the framework does not provide the intended behavior (a.k.a. it's incomplete on purpose),  go over to GitHub
4.3. Find this issue
4.4. See codepen link, containing wanted behavior
4.5. Open link, copy & paste the code
4.6. Rinse and repeat.

Surely I wouldn't

**Comment by laurentpayot** [comment]
@saloniamatteo 

1. Can <kbd>you</kbd> see <kbd>the</kbd> problem <kbd>now</kbd>?
2. Nothing wrong if you want a non-standard behaviour. Just agree it is non-standard.
3. (and 4) By picking imports + purging + minifying Beercs myself, my bundle is 32kB (6.3kB brotli compressed). It takes efforts to minimize the weight to that people with low bandwidth (developing countries) do not wait hours for the page to load. Bloating a bundle simply for the sake of **a single** developper "productivity" is just not acceptable. I have a rather large CSS file to customize beerCSS to my own needs. That’s the way it works.

**Comment by saloniamatteo** [comment]
@laurentpayot Look, I didn't disagree with "too many buttons on the screen" -- your issue was stating that, as well saying it was written nowhere in the specs, I replied that in the guidelines it only says about not too many buttons on the screen; that's clearly something that should be respected but, since this is only an addition to the CSS, it does not matter nor does it apply.

Even if it may be non-standard behavior, it's something that can complete the pre-existing behavior in an intuitive way:

`<a class="button large...` = works
`<a class="button medium...` = works
`<a class="button small...` = works
`<a class="button tiny...` = does NOT work unless the fix written by @leonardorafael is applied

Also, like I said, a couple lines of code aren't going to be that impacting, and trust me, I have a very slow internet where I live. If I get 2Mbps download it's already a lot, even if I have a 200Mbps Wi-Fi plan (not even via cable, Ethernet, it goes that fast).

It's good to see you can reduce the size even further, down to 6kB compressed, may I ask how you did it/which steps you took?

**Comment by laurentpayot** [comment]
@saloniamatteo

If you think inserting buttons in the middle of your text is a good thing for your particular case then you should do it.
It is just that I don’t think it should be included in the bundle because (appart from the size increase) that would make people think this is a common practice.


If you use beercss via CDN, `<a class="button tiny...` will work with the current beercss CDN version if you add the following CSS inside a `style` tag in your _index.html_ file: 
```css
p {
  height: auto!important;
}

p.space,
p.small-space {
  line-height: 24rem;
}

p.medium-space {
  line-height: 32rem;
}

p.large-space {
  line-height: 40rem;
}

button.tiny,
.button.tiny,
.chip.tiny {
  height: 16rem;
  min-height: 16rem;
  font-size: inherit;
  font-weight: inherit;
  line-height: normal;
  padding: 0 8rem;
  vertical-align: unset;
}

.circle.tiny,
.square.tiny,
.diamond.tiny {
  min-width: 16rem;
  min-height: 16rem;
  max-width: 16rem;
  max-height: 16rem;
  height: 16rem;
  padding: 0;
  vertical-align: text-bottom;
}
```
If you say adding these lines is not impacting to you then no problem :slightly_smiling_face: 

I’m not using the CDN version of beercss. I installed beercss via [npm](https://www.npmjs.com/package/beercss). Then I use [Stylus](https://stylus-lang.com/) files to import only what I need from [beercss imports ](https://github.com/beercss/beercss/blob/main/src/cdn/beer.css) and to create my own custom CSS and variables. Stylus will produce a single big file. Then I remove unused CSS from this file with  [purgecss](https://purgecss.com/). Then I minify it with [csso](https://github.com/css/csso). This whole process is automated via npm scripts.
In my index.html page I’m [loading my styles asynchronously](https://web.dev/defer-non-critical-css/) with
```css
<link rel="preload" href="/main.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
```
because I’m actually building a [PWA](https://web.dev/progressive-web-apps/) in [Elm](https://elm-lang.org/) and the JavaScript should not be blocked by the CSS.

If you are new to web development then it takes a while to assimilate all this kind of build processes. People sometimes refer to this as ["javascript fatigue"](https://css-tricks.com/javascript-fatigue/). This is so true! :roll_eyes:

**Comment by KicKerBNU** [comment]
Since we have some disagreement on this new implementation i thinck we should close this issue to mature this idea for now.
