### ISSUE TITLE
Make Pill Buttons the default

### ISSUE THREAD

**Issue by tomatopickle** [beercss/beercss#69]
In Material Design 3, the default button has a 100px radius, since Beercss follows MD3, I think it would be better if it uses pill buttons by default or at least add more border-radius to the current button, maybe make it 12px.

See: https://m3.material.io/components/buttons/overview

**Comment by leonardorafael** [comment]
Hi @tomatopickle ,

After release 2.2.0 we following all specs of buttons and chips. But we can't use the pill button as default because we have a helper called `round`. We want to maintain the same logic in all elements to be easy to use and remember. If you want a "pill button" use `round` helper. So you use `round` when you want any element to be rounded. Ok?
