### ISSUE TITLE
Support for prefix

### ISSUE THREAD

**Issue by c0deship** [beercss/beercss#94]
So I use tailwind and I was eager to use beercss in my project but the class names conflicts with tailwind css, is there a way to allow for prefix option in beercss

**Comment by AlTrAugsburg** [comment]
You could use Bash to edit the css-File of Beercss:

`sed 's/./.beercss-//' beercss.min.css` 

But I wouldn't recommend using two CSS Frameworks in combination, because there could be some side effects. That's because framework don't only define classes, but also set settings directly to some HTML-elements. My recommendation: Copy CSS-settings/classes you like in an extra file to use with Tailwind.

**Comment by myrp-leonardo** [comment]
Hi,

I think It's not a good idea to use 2 css frameworks in a project. Beercss uses semantic sintax and applies some styles directly in html tags.

I found a codepen here (https://codepen.io/leo-bnu/pen/LYWxjVG) showing some tailwindcss examples converted to beercss . My thoughts about it:

1) Has about the the half size of html output, compared with tailwindcss
2) Has dynamic colors ready
3) Has light/dark mode ready

It's a very nice example IMO, without any custom css. Of course it is not 100% equal, because beercss implements the material design 3 system.

**Comment by KicKerBNU** [comment]
@myrp-leonardo I think we can close this issue since we all agreee using two frameworks its not a good practice and make a prefix option right now dont make any sense.

**Comment by BanDroid** [comment]
even this issue is closed, i have some words on this topic.

we dont exactly need prefix for beercss, instead what you need is to prefix the tailwindcss. the reason is simple, you just want to use beercss components while using tailwind for utilities, right? then to avoid classname clashing, put the tailwindcss first then beercss next below it, so this way tailwind wouldn't reset the beercss components but you could still use it for utility.

this is example for nextjs app directory.

```typescript
import "./globals.css";
import "beercss";
import "material-dynamic-colors";
```

> [!CAUTION]
> make sure you have prefix for tailwind so classes like left, right, border, etc. still work for beercss components.
